apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      containers:
        - image: shichoc/dso-demo
          name: dso-demo
          ports:
          - containerPort: 8080
        resources: {}
status: {}